version: '3.7'

services:

  app:
    build: ./
    networks:
      - neti
    depends_on:
      - mongodb
    environment:
      - TZ:"Iran/Tehran"

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - neti
    environment:
      - TZ:"Iran/Tehran"

networks:
  neti:
