version: '3'

services:

  scrape:
    build: .
    depends_on:
      - mongodb
    networks:
      - net1

  mongodb:
    image: mongo
    container_name: mongo_sahamyab
    ports:
      - 27017:27017
    networks:
      - net1

networks:
  net1: