version: '3.7'

services:

  app:
    build: ./
    networks:
      - net1
    depends_on:
      - mongodb
    environment:
      - mongo_uri=mongodb://mongodb:27017

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - net1

networks:
  net1:
