version: '3.7'

services:

  app:
    build: ./
    network_mode: "host" 
    depends_on:
      - mongodb
    environment:
      - mongo_uri=mongodb://mongodb:27017

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    network_mode: "host" 
