version: '3.7'

services:

  app:
    build: ./
    networks:
      - neti
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - neti

networks:
  neti: