version: '3.7'

services:

  app:
    build: ./
    networks:
      - host
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - host

networks:
  host:
    driver: host
    name: host
